"""Module contains class that adds new records to the database."""

import sys
from typing import Dict, Tuple

from life_recorder import helper
from .base import LifeRecorder


class CreateLifeRecorder(LifeRecorder):
    """Implements adding life records to the database."""

    def act(self, identifier: str = None) -> None:
        """Add a new life record to database."""

        if identifier is not None:
            print("It's not needed to have an identifier when adding a life record.")
            print()
            sys.exit()

        # generate record instance
        generated_id, timestamp = self.get_autogenerated_details()
        tag, content = self.get_user_inputs()
        record = helper.construct_record_dict(generated_id, timestamp, tag,
                                              content)

        # add record to database
        updated_database = helper.update_database(self.database, record)
        self.save_records(updated_database)

        helper.add_breakline(helper.print_pretty_record,
                             func_args=[record], both=True)

    def get_user_inputs(self) -> Tuple:
        """Return user inputs to create a record. these inputs are tag and content."""

        # ask for tag of record
        input_message = self.get_input_message("tag")
        tag = input(input_message)
        while tag == "":
            tag = input("Please enter a tag; it can't be blank: ")

        # ask for content of record
        input_message = self.get_input_message("content")
        content = input(input_message)
        while content == "":
            content = input("Please enter a content; it can't be blank: ")

        return tag, content

    def get_autogenerated_details(self) -> Dict:
        """Function gets inputs from user and returns new record."""

        identifier = self.get_identifier()
        timestamp = helper.get_timestamp()

        return identifier, timestamp

    def get_identifier(self) -> int:
        """Function updates and returns the identifier for next record."""

        self.update_last_id()
        return self.last_id

    def update_last_id(self) -> None:
        """Updates last id of the database."""

        self.database["last_id"] += 1

    @property
    def last_id(self):
        """Returns the last id used in the database."""

        return int(self.database["last_id"])


if __name__ == "__main__":
    print(__doc__)
